In [1]:
import pyarrow.parquet as pq

dataset = pq.ParquetDataset(r"E:\MH\VehicleApp\MDI\mpass.parquet")
table = dataset.read() 
df = table.to_pandas()

In [2]:
df

,_operation,_processed_at,_record_id,_source_database,_source_table,_source_type,deleted,id_cuoc_xe,loai_gd,ma_dv_phat_sinh_gd,...,san_pham,so_tai,so_the,so_tien,stt,ten_dv_phat_sinh_gd,ten_in_tren_the,test_1,thoi_diem_giao_dich,trang_thai
0,INITIAL_LOAD,2025-10-22T04:55:34.424475,Mpass_mpass_1,Mpass,mpass,mssql,False,CX671724,N?p ti?n,DV3235,...,Th? Mpass,T32703,0000001075645715,2036901.42,1,Công ty V?n t?i ABC,Nguy?n Van An,,2025-12-27 17:39:17,Thành công
1,INITIAL_LOAD,2025-10-22T04:55:34.427213,Mpass_mpass_2,Mpass,mpass,mssql,False,CX658331,N?p ti?n,DV3875,...,Th? Mpass,T60492,0000001759404043,1734438.14,2,Công ty V?n t?i ABC,Nguy?n Van An,,2025-05-24 07:37:09,Thành công
2,INITIAL_LOAD,2025-10-22T04:55:34.429194,Mpass_mpass_3,Mpass,mpass,mssql,False,CX937876,N?p ti?n,DV0777,...,Th? Mpass,T85424,0000002085681599,2642044.67,3,Công ty V?n t?i ABC,Nguy?n Van An,,2025-10-06 14:07:19,Thành công
3,INITIAL_LOAD,2025-10-22T04:55:34.430879,Mpass_mpass_4,Mpass,mpass,mssql,False,CX132627,N?p ti?n,DV1901,...,Th? Mpass,T34223,0000000534113992,4138408.48,4,Công ty V?n t?i ABC,Nguy?n Van An,,2025-08-04 08:12:22,Thành công
4,INITIAL_LOAD,2025-10-22T04:55:34.432536,Mpass_mpass_5,Mpass,mpass,mssql,False,CX220609,N?p ti?n,DV1112,...,Th? Mpass,T08232,0000000274647772,4034300.48,5,Công ty V?n t?i ABC,Nguy?n Van An,,2023-08-02 20:52:30,Thành công
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,INITIAL_LOAD,2025-10-22T04:55:35.875095,Mpass_mpass_997,Mpass,mpass,mssql,False,CX281890,Thanh toán,DV3934,...,Th? ETC,T59727,0000000681362433,3815628.38,997,Ð?i tác Liên k?t,Nguy?n Van An,,2023-03-21 19:11:48,Thành công
997,INITIAL_LOAD,2025-10-22T04:55:35.876449,Mpass_mpass_998,Mpass,mpass,mssql,False,CX867694,Thanh toán,DV1377,...,Th? ETC,T29201,0000001124606443,3100309.99,998,Ð?i tác Liên k?t,Nguy?n Van An,,2024-10-02 19:30:15,Thành công
998,INITIAL_LOAD,2025-10-22T04:55:35.877756,Mpass_mpass_999,Mpass,mpass,mssql,False,CX236422,Thanh toán,DV4143,...,Th? ETC,T79110,0000001918964104,4199850.09,999,Ð?i tác Liên k?t,Nguy?n Van An,,2023-07-20 20:42:47,Thành công
999,INITIAL_LOAD,2025-10-22T04:55:35.879032,Mpass_mpass_1000,Mpass,mpass,mssql,False,CX542430,Thanh toán,DV4830,...,Th? ETC,T87370,0000000061233708,1321605.89,1000,Ð?i tác Liên k?t,Nguy?n Van An,,2024-06-19 00:53:03,Thành công
1000,DELETE,2025-10-22T04:56:14.560576,Mpass_mpass_1001,Mpass,mpass,mssql,True,CX1001,Thanh toán,DV001,...,Gói Tháng A,TAI001,8888123412341234,600000.00,1001,Công ty Vận tải MCC,SEONGHYEON,,2025-10-22 10:00:00,Hoàn tất

In [25]:
# Cách 1: dùng .shape
num_rows = df_filtered.shape[0]

# Cách 2: dùng len()
num_rows = len(df_filtered)

print("Số dòng:", num_rows)

Số dòng: 1002